services:
  - type: web
    name: pioneer-trader
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_SECRET  # <--- UPDATED TO MATCH YOUR KEY
        sync: false
      - key: PORT
        value: 10000