version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: infra/Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../backend:/app/backend
    restart: always

  streamlit:
    build:
      context: ../
      dockerfile: infra/Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    volumes:
      - ../streamlit_app:/app/streamlit_app
    depends_on:
      - backend
    restart: always
